# Generated by Django 6.0.6 on 2026-06-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_update_priority_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='priority',
            field=models.CharField(default='Normal', max_length=20),
        ),
    ]
