# Generated by Django 6.0.6 on 2026-06-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_supportticket_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='project',
            field=models.CharField(choices=[('CRM', 'CRM'), ('ERP', 'ERP'), ('HRMS', 'HRMS'), ('Website', 'Website')], default='CRM', max_length=50),
        ),
    ]
